In [ ]:
import pandas as pd
import os
import shutil
data = pd.read_csv('./data/grade/KL_Grade.csv', header=0, encoding='cp949')
df = pd.DataFrame(data)
df

,Unnamed: 0,File_name_pic,real_xml,KL0,KL1,KL2,KL3,KL4,KL_Grade
0,0,00000104_1.jpg,00000104_1.xml,1,0,0,0,0,0
1,1,00000104_2.jpg,00000104_2.xml,1,0,0,0,0,0
2,2,00000204_1.jpg,00000204_1.xml,1,0,0,0,0,0
3,3,00000204_2.jpg,00000204_2.xml,1,0,0,0,0,0
4,4,00000304_1.jpg,00000304_1.xml,0,0,1,0,0,2
...,...,...,...,...,...,...,...,...,...
8262,8262,00000296_0.jpg,00000296_0.xml,0,0,0,0,1,4
8263,8263,00000297_0.jpg,00000297_0.xml,0,0,0,0,1,4
8264,8264,00000298_0.jpg,00000298_0.xml,0,0,0,0,1,4
8265,8265,00000299_0.jpg,00000299_0.xml,0,0,0,0,1,4
8266,8266,00000300_0.jpg,00000300_0.xml,0,0,0,0,1,4

In [ ]:
for i in range(len(df)):
    if df['File_name_pic'][i][0:10] == df['real_xml'][i][0:10]:
        pass
    elif df['name'][i][0] != df['temp'][i][0]:
        print('이상있음 : {}' .format(df['name'][i]))

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8267 entries, 0 to 8266
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     8267 non-null   int64
 1   File_name_pic  8267 non-null   object
 2   real_xml       8267 non-null   object
 3   KL0            8267 non-null   int64
 4   KL1            8267 non-null   int64
 5   KL2            8267 non-null   int64
 6   KL3            8267 non-null   int64
 7   KL4            8267 non-null   int64
 8   KL_Grade       8267 non-null   int64
dtypes: int64(7), object(2)
memory usage: 581.4+ KB

In [ ]:
df=df.drop_duplicates(['File_name_pic'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8261 entries, 0 to 8266
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     8261 non-null   int64
 1   File_name_pic  8261 non-null   object
 2   real_xml       8261 non-null   object
 3   KL0            8261 non-null   int64
 4   KL1            8261 non-null   int64
 5   KL2            8261 non-null   int64
 6   KL3            8261 non-null   int64
 7   KL4            8261 non-null   int64
 8   KL_Grade       8261 non-null   int64
dtypes: int64(7), object(2)
memory usage: 645.4+ KB

In [ ]:
df.to_csv('./data/grade/KL_grade1st.csv', index=False) # 저장하기

In [ ]:
src = '../../tempxray/Picture_Xml/All_picture/'
dest = '../../final/g4/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 4]['File_name_pic']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_xml/'
dest = '../../final/gx4/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 4]['real_xml']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_picture/'
dest = '../../final/g3/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 3]['File_name_pic']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_xml/'
dest = '../../final/gx3/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 3]['real_xml']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_picture/'
dest = '../../final/g2/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 2]['File_name_pic']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_xml/'
dest = '../../final/gx2/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 2]['real_xml']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_picture/'
dest = '../../final/g1/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 1]['File_name_pic']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_xml/'
dest = '../../final/gx1/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 1]['real_xml']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_picture/'
dest = '../../final/g0/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 0]['File_name_pic']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

In [ ]:
src = '../../tempxray/Picture_Xml/All_xml/'
dest = '../../final/gx1/'

In [ ]:
for i, name in enumerate(df[df['KL_Grade'] == 0]['real_xml']):
    try:
        shutil.move(os.path.join(src, name), os.path.join(dest, name))
    except FileNotFoundError:
        print(f'{name} 파일이 존재하지 않습니다' )

#### csv 에만 있는 경우 / 실제 jpg, xml 없음
* output으로 출력

#### csv 에 없는 경우 / 실제 jpg, xml 있음  
* 디렉토리에 남게됨